### ISSUE TITLE
[bug] When logged in, refreshing the page hides the tabs

### ISSUE THREAD

**Issue by marcoviappiani** [tropicalsubmarine/tropicalbs#127]
After having logged in, even as an admin, if you refresh the page all the tabs disappear.
Expectation is that all tabs should still be visible.

**Comment by marcoviappiani** [comment]
I noticed it's happening because vm.tabs is an empty array so it's not getting assigned or filtered correctly. My intuition is that it has to do with the function 

```
function filterTabs () {
    vm.tabs = _.filter(navService.getTabs(), function (tab) {
    // intersection returns empty array when no intersection is found
    // thus we can use this to determine whether or not a tab should be visible
    return _.intersection(tab.visibleRoles, vm.user.roles).length > 0;
    });
  }
```

**Comment by RRDuke** [comment]
I think we could solve this by refactoring the list of currently visible tabs into the nav service instead of the nav controller.
