### ISSUE TITLE
mirror of mean.js

### ISSUE THREAD

**Issue by mg1075** [tropicalsubmarine/tropicalbs#258]
It would be cool - probably just a pipe dream - if this project mirrored mean.js in **all** aspects (except for mongo and mongoose, obviously).

**Comment by codydaig** [comment]
The goal of this project was to create mean.js, but with material design, sql, and have a small CMS for simple pages.

**Comment by mg1075** [comment]
OK.
Just found PEAN.JS. Maybe this could be the answer.
https://github.com/StetSolutions/pean
