### ISSUE TITLE
Correction of dependency injection to allow minification

### ISSUE THREAD

**Issue by marcoviappiani** [tropicalsubmarine/tropicalbs#79]
We need to update the Angular files to move from implicit annotation (currently used on many files) to explicit annotation (dependency injection).
If not, minification will break our app.
info at https://docs.angularjs.org/guide/di

**Comment by marcoviappiani** [comment]
just to add a small clarification since I expect it might come up: 
When we access the module from another file, that one shouldn't need the injection as we're using the unnamed modules pattern. Example: 

```
// Main Controller File - this is basically our app.js
angular.module('my-controllers',[]);

// File of Controller One
angular.module('my-controllers')
    .controller('oneCtrl',[...]);

//File of Controller Two
angular.module('my-controllers')
    .controller('twoCtrl',[...]);
```

A more detailed example is available at http://stackoverflow.com/questions/19957280/angularjs-best-practices-for-module-declaration

**Comment by codydaig** [comment]
https://github.com/johnpapa/angular-styleguide

**Comment by RRDuke** [comment]
This is done
